### ISSUE TITLE
CTD on launch in v1.2.9 from FontFactory changes

### ISSUE THREAD

**Issue by jzebedee** [BUTR/Bannerlord.BLSE#94]
BLSE crashes on launch after changes made in the v1.2.9 release, because

`TaleWorlds.GauntletUI.FontFactory::AddFontDefinition(System.String,System.String,TaleWorlds.TwoDimension.SpriteData)` 

turned into:

`System.Boolean TaleWorlds.GauntletUI.FontFactory::TryAddFontDefinition(System.String,System.String,TaleWorlds.TwoDimension.SpriteData)`

```
BLSE Exception:
Version: 1.4.11.0

Type: System.MissingMethodException
Message: Method not found: 'Void TaleWorlds.GauntletUI.FontFactory.AddFontDefinition(System.String, System.String, TaleWorlds.TwoDimension.SpriteData)'.
Source: Bannerlord.LauncherEx
CallStack:
   at Bannerlord.LauncherEx.ResourceManagers.FontFactoryManager.LoadAllFontsPostfix(FontFactory& __instance)
   at TaleWorlds.GauntletUI.FontFactory.LoadAllFonts_Patch1(FontFactory this, SpriteData spriteData)
   at TaleWorlds.GauntletUI.UIContext.Initialize()
   at TaleWorlds.MountAndBlade.Launcher.Library.StandaloneUIDomain.Update()
   at TaleWorlds.TwoDimension.Standalone.WindowsFramework.MessageLoop()
   at TaleWorlds.TwoDimension.Standalone.WindowsFramework.Start()
   at TaleWorlds.MountAndBlade.Launcher.Library.Program.Main(String[] args)
   at Bannerlord.BLSE.Shared.LauncherEx.Launch(String[] args)
   at Bannerlord.BLSE.Shared.Program.Main(String[] args)
   at Bannerlord.BLSE.NETFrameworkLoader.Launch(String[] args)
   at Bannerlord.BLSE.Program.Main(String[] args)
```

It looks like it would be a simple patch, but the reference assemblies aren't updating because of https://github.com/BUTR/Bannerlord.ReferenceAssemblies/issues/82

**Comment by Aragas** [comment]
Closed by #95
