### ISSUE TITLE
CTD on launch in v1.2.9 from PropertyOwnerObject changes

### ISSUE THREAD

**Issue by jzebedee** [BUTR/Bannerlord.BLSE#96]
BLSE crashes on launch after changes made in the v1.2.9 release, because

`Void TaleWorlds.GauntletUI.PropertyOwnerObject.OnPropertyChanged(System.Object, System.String)`

was removed and replaced with strongly typed and generic overloads:

`System.Void TaleWorlds.GauntletUI.PropertyOwnerObject::OnPropertyChanged<T>(T,System.String)`

```
BLSE Exception:
Version: 1.4.12.0

Type: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
CallStack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TaleWorlds.GauntletUI.PrefabSystem.WidgetExtensions.SetWidgetAttribute(UIContext context, Object target, String name, Object value)
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBinding()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletView.RefreshBindingWithChildren()
   at TaleWorlds.GauntletUI.Data.GauntletMovie.LoadMovie()
   at TaleWorlds.GauntletUI.Data.GauntletMovie.Load(UIContext context, WidgetFactory widgetFactory, String movieName, IViewModel datasource, Boolean doNotUseGeneratedPrefabs, Boolean hotReloadEnabled)
   at TaleWorlds.MountAndBlade.Launcher.Library.LauncherUI.Initialize_Patch1(LauncherUI this)
   at TaleWorlds.MountAndBlade.Launcher.Library.StandaloneUIDomain.Update()
   at TaleWorlds.TwoDimension.Standalone.WindowsFramework.MessageLoop()
   at TaleWorlds.TwoDimension.Standalone.WindowsFramework.Start()
   at TaleWorlds.MountAndBlade.Launcher.Library.Program.Main(String[] args)
   at Bannerlord.BLSE.Shared.LauncherEx.Launch(String[] args)
   at Bannerlord.BLSE.Shared.Program.Main(String[] args)
   at Bannerlord.BLSE.NETFrameworkLoader.Launch(String[] args)
   at Bannerlord.BLSE.Program.Main(String[] args)


Inner 
Type: System.MissingMethodException
Message: Method not found: 'Void TaleWorlds.GauntletUI.PropertyOwnerObject.OnPropertyChanged(System.Object, System.String)'.
Source: Bannerlord.LauncherEx
CallStack:
   at Bannerlord.LauncherEx.Widgets.LauncherToggleButtonWidget.set_IsSelected(Boolean value)
```

**Comment by jzebedee** [comment]
This could be solved with a workaround like #95, but I think it's better to leave it alone and target the new reference assemblies, since this is a hot path. Once the new reference is added, it should rebuild and target the bool or generic overload without any code changes needed.

**Comment by Aragas** [comment]
Hm, not sure here. The `OnPropertyChanged` generic was introduced somewhere at v1.1.x and I did develop some fix for that. Will investigate

**Comment by Aragas** [comment]
I think this might have been an issue on your end, but only because I've overengineered the MSBuild stuff for backwards compatibility.
Basically, BLSE has right now three assemblies for LauncherEx - for game versions v1.0.0-v1.0.3, for game versions v1.1.0-v1.1.4 and for v1.2.0 and beyond
I believe somehow you've triggered the v1.0.0 instead of v1.2.0
BLSE seems to be working well with the PR you have already done
